services:
  - type: web
    name: eco-shop
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: node dist/main.min.js
    envVars:
      - key: TELEGRAM_TOKEN
        fromSecret: TELEGRAM_TOKEN
      - key: TELEGRAM_CHAT_ID
        fromSecret: TELEGRAM_CHAT_ID
